import { useEffect,useMemo,useState } from "react";
import { demoProducts,demoSettings } from "./demo";
import { configured,supabase } from "./lib/supabase";
import type { CartItem,Product,StoreSettings } from "./types";
const money=(cents:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(cents/100);
export function Storefront({navigate}:{navigate:(to:string)=>void}){
 const [products,setProducts]=useState<Product[]>(demoProducts); const [settings,setSettings]=useState<StoreSettings>(demoSettings); const [cart,setCart]=useState<CartItem[]>([]); const [cartOpen,setCartOpen]=useState(false);
 useEffect(()=>{if(!supabase)return;Promise.all([supabase.from("products").select("*").eq("active",true).order("sort_order"),supabase.from("store_settings").select("*").limit(1).maybeSingle()]).then(([p,s])=>{if(p.data?.length)setProducts(p.data as Product[]);if(s.data)setSettings(s.data as StoreSettings)})},[]);
 const total=useMemo(()=>cart.reduce((sum,item)=>sum+item.product.price_cents*item.quantity,0),[cart]);
 const add=(product:Product)=>{setCart(items=>{const found=items.find(i=>i.product.id===product.id);return found?items.map(i=>i.product.id===product.id?{...i,quantity:i.quantity+1}:i):[...items,{product,quantity:1}]});setCartOpen(true)};
 const adjust=(id:string,delta:number)=>setCart(items=>items.map(i=>i.product.id===id?{...i,quantity:i.quantity+delta}:i).filter(i=>i.quantity>0));
 return <><div className="announcement">{settings.announcement}</div><header className="store-header"><button className="wordmark" onClick={()=>navigate("/")}><span>The</span> Bird’s Nest <small>Flower Shop · Columbia, Louisiana</small></button><nav><a href="#shop">Shop</a><a href="#about">About</a><a href={`tel:${settings.phone.replace(/\D/g,"")}`}>Call</a><button className="cart-button" onClick={()=>setCartOpen(true)}>Bag <b>{cart.reduce((n,i)=>n+i.quantity,0)}</b></button></nav></header>
 <main><section className="flower-hero"><div><p className="script">Flowers for the moments that matter</p><h1>Made with care.<br/>Given with love.</h1><p>Fresh arrangements from your hometown flower shop in downtown Columbia.</p><a className="shop-button" href="#shop">Shop arrangements</a></div><div className="hero-photo"><img src="https://irp-cdn.multiscreensite.com/md/dmtmpl/9e900b9e-711d-4a37-bae9-9adab2bb66d1/dms3rep/multi/Group-1-1932x1027.jpg" alt="Pink flower arrangement"/></div></section>
 <section className="shop-section" id="shop"><div className="section-title"><p className="script">From our cooler to their day</p><h2>Bouquet shop</h2><p>Seasonal flowers may vary. Every arrangement is made with the same care.</p></div><div className="product-grid">{products.map(p=><article className="product-card" key={p.id}><div className="product-photo"><img src={p.image_url} alt={p.name}/>{p.featured&&<span>Shop favorite</span>}</div><div className="product-info"><div><p>{p.category}</p><h3>{p.name}</h3></div><strong>{money(p.price_cents)}</strong></div><p>{p.description}</p><button disabled={!settings.accepting_orders} onClick={()=>add(p)}>{settings.accepting_orders?"Add to bag":"Call to order"}</button></article>)}</div></section>
 <section className="about-section" id="about"><div><p className="script">Your hometown florist</p><h2>Say it with flowers.</h2><p>Welcome to The Bird’s Nest, your go-to place for beautiful flowers right here in downtown Columbia. Our florists put together arrangements for celebrations, sympathy, gratitude, and the ordinary days that deserve something beautiful.</p><a href={`tel:${settings.phone.replace(/\D/g,"")}`}>Call {settings.phone}</a></div><img src="https://irp.cdn-website.com/cecc5eca/dms3rep/multi/opt/IMG_9971-1920w.png" alt="Fresh flowers at The Bird's Nest"/></section></main>
 <footer><div><strong>{settings.store_name}</strong><p>{settings.address}</p></div><div><strong>Hours</strong><p>{settings.hours}</p></div><div><strong>Order by phone</strong><a href={`tel:${settings.phone.replace(/\D/g,"")}`}>{settings.phone}</a></div><button className="quiet" onClick={()=>navigate("/admin")}>Shop login</button></footer>
 {cartOpen&&<div className="cart-layer" onClick={()=>setCartOpen(false)}><aside className="cart-drawer" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setCartOpen(false)}>×</button><p className="script">Your flowers</p><h2>Shopping bag</h2>{cart.length===0?<p>Your bag is empty.</p>:<>{cart.map(i=><div className="cart-line" key={i.product.id}><img src={i.product.image_url} alt=""/><div><strong>{i.product.name}</strong><span>{money(i.product.price_cents)}</span><div><button onClick={()=>adjust(i.product.id,-1)}>−</button><b>{i.quantity}</b><button onClick={()=>adjust(i.product.id,1)}>+</button></div></div></div>)}<div className="cart-total"><span>Total</span><strong>{money(total)}</strong></div><button className="checkout" disabled>Online checkout will open after payments are connected</button><a className="phone-order" href={`tel:${settings.phone.replace(/\D/g,"")}`}>Call {settings.phone} to order</a></>}</aside></div>}
 {!configured&&<div className="demo-badge">Store preview · database not connected</div>}</>;
}
